### PR TITLE
Update Dropify.vue

### PR DESCRIPTION
**Pull request by Thalad**
possibilité de supprimer une image qui n'a pas été uploadé mais séléctionné

### CODE REVIEW

**Comment by khofaai** [comment]
Hi @Thalad , can you explain more and give me a use case if possile ? 
because `setImageSrc` is only to set an image passed via `src` props  when the component mounts,
Thanks

**Comment by Thalad** [comment]
Hi @khofaai,
the setImageSrc() function is also used in the watch for src key. 
In my case I want to be able to delete an image displayed via the src props and not uploaded and that is impossible for me

**Comment by khofaai** [comment]
my bad, yes in that case we can make it shorter like 
```js
const src = this.src === undefined || this.src === null ? '' : this.src;
this.images = { src }
```
in the case the props is `null` or `undefined` we pass an empty string otherwise we take `src` value,
what do you think ?

**Comment by Thalad** [comment]
perfect that suits me ! thank you for your reactivity

**Comment by khofaai** [comment]
the same for you :)

**Comment by khofaai** [comment]
@Thalad i can't publish the new version in npm for the moment, i will do it later today, Thanks

**Comment by Thalad** [comment]
ok thanks !

**Pull request merged**
